spring.application.name=demo

spring.profiles.active=local

# JPA setting
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# Email setting
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Allow special characters in URL query
server.tomcat.relaxed-query-chars=[,]

# Health check info
management.endpoint.health.show-details=always
management.health.probes.enabled=true
management.health.mail.enabled=false
management.endpoint.health.group.readiness.include=db,redis
management.endpoint.health.group.liveness.include=ping
